server:
  port: 9090

spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/geom3d_db
    username: postgres 
    password: postgres
    driverClassName: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/GeoCalc3D

logging:
  level:
    root: INFO
    "[org.springframework.web]": DEBUG
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE
    "[org.springframework.security]": DEBUG
    "[org.springframework.boot.autoconfigure]": DEBUG

app:
    name: GeoCalc3D

